### ISSUE TITLE
Add custom baseline parameter functionality

### ISSUE THREAD

**Issue by class125good126** [DeEpinGh0st/WindowsBaselineAssistant#1]
通常每个项目的基线要求都不一样，建议增加自定义基线标准和检测项功能，这样可以适用于更广泛的场景

**Comment by DeEpinGh0st** [comment]
感谢反馈
你可以通过修改item.xml,添加检测项或修改检测标准

**Comment by class125good126** [comment]
你好!!!
***@***.***;麻烦请将邮件发往此邮箱,非常感谢您对我工作的支持!!!
