### ISSUE TITLE
哪个版本的基线

### ISSUE THREAD

**Issue by songyao199681** [DeEpinGh0st/WindowsBaselineAssistant#2]
师傅请问是哪个基线，cis的还是等保的，cis的我用powershell写过，你这个不太全

**Comment by DeEpinGh0st** [comment]
没有具体到是什么标准的基线,师傅可以按照自己使用的powershell翻译为工具可识别的规则文件.工具自带的规则文件只作为一个基本参考

**Comment by songyao199681** [comment]
哦哦，了解了，之前查看cis写的后面太多了没写完了
