### ISSUE TITLE
secedit信息生成失败

### ISSUE THREAD

**Issue by Work-hard-and-change** [DeEpinGh0st/WindowsBaselineAssistant#3]
你好请问这个怎么解决[
![1709541443196](https://github.com/DeEpinGh0st/WindowsBaselineAssistant/assets/85383451/242abf27-b5d1-4ef7-871b-5d18a49bb40f)
](url)

**Comment by DeEpinGh0st** [comment]
师傅可以检查下系统是否有secedit命令

**Comment by Work-hard-and-change** [comment]
大佬你好  公司领导让我按照你的源码 二次开发一个可以兼容一些win老系统 但我只是一个实习生 我不会咋办QAQ

**Comment by DeEpinGh0st** [comment]
@Work-hard-and-change 请将联系方式发送至ouhmgoofrp23@outlook.com
